export const iconsImages = (icons: number) => {
  switch (icons) {
    case 1:
      return require(`../resources/weather-icons/1.png`);
    case 2:
      return require(`../resources/weather-icons/2.png`);
    case 3:
      return require(`../resources/weather-icons/3.png`);
    case 4:
      return require(`../resources/weather-icons/4.png`);
    case 5:
      return require(`../resources/weather-icons/5.png`);
    case 6:
      return require(`../resources/weather-icons/6.png`);
    case 7:
      return require(`../resources/weather-icons/7.png`);
    case 8:
      return require(`../resources/weather-icons/8.png`);
    case 11:
      return require(`../resources/weather-icons/11.png`);
    case 12:
      return require(`../resources/weather-icons/12.png`);
    case 13:
      return require(`../resources/weather-icons/13.png`);
    case 14:
      return require(`../resources/weather-icons/14.png`);
    case 15:
      return require(`../resources/weather-icons/15.png`);
    case 16:
      return require(`../resources/weather-icons/16.png`);
    case 17:
      return require(`../resources/weather-icons/17.png`);
    case 18:
      return require(`../resources/weather-icons/18.png`);
    case 19:
      return require(`../resources/weather-icons/19.png`);
    case 20:
      return require(`../resources/weather-icons/20.png`);
    case 21:
      return require(`../resources/weather-icons/21.png`);
    case 22:
      return require(`../resources/weather-icons/22.png`);
    case 23:
      return require(`../resources/weather-icons/23.png`);
    case 25:
      return require(`../resources/weather-icons/25.png`);
    case 26:
      return require(`../resources/weather-icons/26.png`);
    case 29:
      return require(`../resources/weather-icons/29.png`);
    case 32:
      return require(`../resources/weather-icons/32.png`);
    case 33:
      return require(`../resources/weather-icons/33.png`);
    case 34:
      return require(`../resources/weather-icons/34.png`);
    case 35:
      return require(`../resources/weather-icons/35.png`);
    case 36:
      return require(`../resources/weather-icons/36.png`);
    case 37:
      return require(`../resources/weather-icons/37.png`);
    case 38:
      return require(`../resources/weather-icons/38.png`);
    case 39:
      return require(`../resources/weather-icons/39.png`);
    case 40:
      return require(`../resources/weather-icons/40.png`);
    case 41:
      return require(`../resources/weather-icons/41.png`);
    case 42:
      return require(`../resources/weather-icons/42.png`);
    case 43:
      return require(`../resources/weather-icons/43.png`);
    case 44:
      return require(`../resources/weather-icons/44.png`);
  }
};
